### ISSUE TITLE
Documentation on run.sh, Koop, heroku and AGOL map

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#145]
We should write up step-by-step guides on how the above things work.

**Comment by hellonewman** [comment]
I'm thinking: Max can write about run.sh (how it works and how to run it to update the data), Matt can write about Koop and Heroku, Melinda can write about AGOL, and I'll fill in the gaps.

**Comment by hellonewman** [comment]
I am also fleshing out our Excel table explaining all the data source and various notes and will add that to the readme when complete

**Comment by hellonewman** [comment]
We should also add in documentation to remind us to add an new data prep scripts to the sourcing scripts that source the R and Python scripts per issue #138

**Comment by maxachis** [comment]
I'm ready to start tackling this so we can get it off of our issue list. I'll need Ellie's feedback/knowledge on some of this because I'm not sure what has and has not been completed:

1. My run.sh script contains comments indicating what each step does. The main [README](https://github.com/CodeForPittsburgh/food-access-map-data/blob/master/README.md) currently indicates (under the confusingly-named* "food-access-map-data" header) how run.sh is run. Is this sufficient, or is anything else needed?
2. I don't see documentation on how AGOL, Koop, or Heroku work. If we don't have those, I can set aside time where I can talk with Melinda and Matt about how these are put together. Just give me the word.

* Should we change this header name to something a little more clear, such as "How We Put Together Our Data" or something else?

**Comment by maxachis** [comment]
Everything looks good, and we don't use AGOL, Koop, or Heroku anymore (it's all just hosted on Git), so we can close this!
