### ISSUE TITLE
Create User Personas

### ISSUE THREAD

**Issue by ryangeraghty** [CodeForPittsburgh/food-access-map-data#186]
As a Code For Pittsburgh project team, we want to describe the anticipated user personas for this project so that we can make design decisions with those individuals in mind.

First Initial Targeted Users:
1. Service Providers/Navigators
2. Consumers

Sources for data:
1, Service Providers/Navigators: Employees of existing partner organizations
2. Consumers - To be identified

Deliverable: Google Slide persona description

**Comment by maxachis** [comment]
Closing this because we feel fairly confident in who our anticipated audience is with this -- primarily low-income people seeking assistance from food assistance organizations. We don't need to develop an explicit user personas, although someone is certainly welcome to revive this if they're willing to do it!
