### ISSUE TITLE
Redo geocoding using non-Google service

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-map-data#39]
Need to use a free geocoder instead of Google to get lat/longs for our datasets, as Google requires displaying geocoded data on its own maps.

Max Chis is working on switching out geocoding with WRPDC's Geomancer tool: https://tools.wprdc.org/geo/

**Comment by maxachis** [comment]
After talking about this with Melinda, I'm going to direct my attention towards the Allegheny County Geocoder instead. Apparently it is updated weekly, whereas Geomancer hasn't been updated (at least not on the Github) since 2018.
[http://gisdata.alleghenycounty.us/arcgis/rest/services/Geocoders/Composite/GeocodeServer](http://gisdata.alleghenycounty.us/arcgis/rest/services/Geocoders/Composite/GeocodeServer)

**Comment by hellonewman** [comment]
Done! Max replaced our google geocoding with the Mapbox geocoded.
